### ISSUE TITLE
filter request

### ISSUE THREAD

**Issue by mloballer** [navarog/wingsearch#1]
Hello, this tool is an awesome reference for an amazing game.

Was wondering, like with TM card list can you add some more filters?

I think filtering by pink, brown, blue, and no abilities would be nice to have.

Also, be to able to filter by nest type

And last, this one might be able to be difficult but to filter by food type needed to play the bird. 

Thanks!!

**Comment by navarog** [comment]
Hi! Thanks for great suggestions, I will definitely add them in the near future.
