### ISSUE TITLE
Incorrect dutch capitalization of bird powers

### ISSUE THREAD

**Issue by erikhuizinga** [navarog/wingsearch#10]
I'm not sure if you edited the texts, but now the first letter of the power is still capitalized. However, if the power contains more than 1 sentence, the new sentences are not capitalized. That should be the other way around, e.g. (_Corvus cornix_):

Currently is:

```
EINDE RONDE: Kies 1 andere speler. voor elke actiesteen die hij op zijn [grassland] heeft, stop je 1 [card] uit je hand onder deze vogel weg. trek dan hetzelfde aantal [card].
```

Should be:

```
EINDE RONDE: kies 1 andere speler. Voor elke actiesteen die hij op zijn [grassland] heeft, stop je 1 [card] uit je hand onder deze vogel weg. Trek dan hetzelfde aantal [card].
```

_Originally posted by @erikhuizinga in https://github.com/navarog/wingsearch/issues/8#issuecomment-728775171_

**Comment by navarog** [comment]
Oh, so it was not a bug, but a feature, my bad. I reverted the changes to the original, many thanks for letting me know.
