### ISSUE TITLE
A question about the birds' images

### ISSUE THREAD

**Issue by finalmaster24** [navarog/wingsearch#11]
How can I view the bird's images? I wanna see more than just their silhouettes.

**Comment by navarog** [comment]
This is not possible. Silhouettes are there to respect copyright laws. If you want to preview birds from a new expansion, I would suggest checking out some videos where they show each bird art, e.g. for oceania you can check out https://www.youtube.com/watch?v=y8sHqNApuOg

**Comment by finalmaster24** [comment]
I see. That's good for you to do so.

And no, I'm not being sarcastic. I'm sincerely respecting you for respecting copyright laws.
