### ISSUE TITLE
Search on language dependant bonus cards doesn't work

### ISSUE THREAD

**Issue by Touniouk** [navarog/wingsearch#13]
Hello, 

The "Search birds by applicable bonus cards" function does not work in other languages, on bonus cards such as "Historian" and "Anatomist" the list of filtered birds is always the same regardless of language.

The filtered birds also do not correspond with the English names, for example "Abott's Booby" is not present for "Historian" while "magpie Lark" is. I checked and the filtered birds correspond with what is in master.json, just that the ticks in master.json are incorrect (in English at least, which I assumed it was based on).

Ideally language contributors would also be able to specify is birds qualify for the affected bonus cards.

The full list of language dependant bonus cards is:
Anatomist, Cartographer, Historian and Photographer.

**Comment by navarog** [comment]
Thank you very much for the observation!

I will fix the data mismatch in english version, it seems oceania birds need to be reviewed. 

I wasn't aware of language dependent bonus cards, that's a good point. Which language do you use? I could add the columns to the [i18n](https://github.com/navarog/wingsearch/tree/master/i18n) files with predefined values of applicable bonuses from english version. Could you then take a few minutes and revise cards for your language?

**Comment by navarog** [comment]
I have fixed the english version for these bonuses in #14 and added columns to specify differences between different languages in #15. @Touniouk, it's up to you now to provide the correct data for your language 🙂 And once again, many thanks for the suggestion!

**Comment by navarog** [comment]
Closing with #16.
