### ISSUE TITLE
Filter by food cost

### ISSUE THREAD

**Issue by erikhuizinga** [navarog/wingsearch#18]
It's already possible to filter by food types. It would be nice to filter by food cost. For example, I'd like to know what birds cost 1 food only, or exactly 3 food, or have an 'A or B' food cost, or only eat the same food type, or 2 or 3 food types.

There are various options for food cost filters, but allowing to filter by number of food tokens seems the best first stem, IMHO. That would allow me to easily find the birds that score a lot of points for just 1 (or 0) food, or have a high egg capacity, for example. I can imagine that a slider like the egg capacity or feather points can be used for this.

**Comment by erikhuizinga** [comment]
Another suggested solution: add clickable buttons for all actual food costs. There shouldn't be too many.

So:

- 🐛
- 🐛 + 🐛
- 🐛 + 🐛 + 🐛
- etc. until all options are shown.

If displayed in a grid, this might not take too much UI space, depending on how many different food lists there are.

The current food filters can stay. When e.g. the global 🐛 food filter is disabled, all the other buttons showing a 🐛 should also be disabled. Clicking one of the specific 🐛-containing filters should re-enable the global 🐛 food filter, but leave the other specific filters disabled.

**Comment by navarog** [comment]
I am not sure what use case would it solve, I vote for simple design over more buttons clickable in few situations.
