### ISSUE TITLE
Feature request: white powers vs no power

### ISSUE THREAD

**Issue by Touniouk** [navarog/wingsearch#19]
It would be handy to be able to filter between white power and no power birds, currently they're both in the same category (as with the game), I assume another "no power" category could be added next to the white power one.

This is only tangibly related but the appendices sorts bird power by power type such as food gaining power or card drawing power, being able to add those tags would also be interesting.

**Comment by navarog** [comment]
I am not sure what use case would it solve, I vote for simple design over another button clickable in few situations.
