### ISSUE TITLE
Query 'chaff' does not return Common Chiffchaff

### ISSUE THREAD

**Issue by erikhuizinga** [navarog/wingsearch#2]
Searching for 'chaff' doesn't result in the Common Chiffchaff. More in general, substrings of bird names are not returned from the search queries.

Suggestions:

- Search for queries as a substring of the bird's name.
- Use a more fuzzy search algorithm. There should be off-the-shelf libs for this. E.g. when searching 'blbrd' the results would contain the bluebirds and blackbirds.

**Comment by navarog** [comment]
I am using [flexsearch](https://github.com/nextapps-de/flexsearch) library for indexing and searching. I've set up full indexing on bird titles, so queries like 'chaff' should be possible. I wasn't able to set more fuzzy search algorithm within bounds of this library, probably more custom encoder would be needed as this fuzzy search was returning too much false positives. I will investigate the issue further in the future and think about the best trade off here.
