### ISSUE TITLE
Food sorting

### ISSUE THREAD

**Issue by Touniouk** [navarog/wingsearch#21]
Hello, I think the food sorting could use some improvement. I don't think picking food to exclude is particularly useful for most search cases. I would be more useful to pick foods that must be in the cost.

For example for now if I want to see how many birds eat fish, the only way is to filter by fishery manager. However you cannot do that with invertebrate, and nectar, and it becomes kinda annoying to combine food combinations and habitats etc...

I think it's more useful if you ticked which food MUST be included. So for example if I want to see which birds eat invertebrate AND fish, I would pick invertebrate AND fish and it would filter out birds that have neither in their food cost. ex:
![image](https://user-images.githubusercontent.com/34683406/174458610-bbc65ab5-f162-44a4-b93f-b395eef4c04c.png)

In that case to see all birds, none of the food must be ticked

I looked at it a bit and the way to implement that is to change `eatsForbiddenFood` to 
```javascript
const eatsFood = (card: BirdCard, mustHaveFood: string[]): boolean => {
    const foodKeys = ['Invertebrate', 'Seed', 'Fruit', 'Fish', 'Rodent', 'Nectar', 'Wild (food)']
    const birdFood = foodKeys.filter(key => card[key]).map(key => key.toLowerCase())
    return !!mustHaveFood.every(food => birdFood.includes(food))
}
```
And then change
```javascript
const mustHaveFood = Object.entries(action.food).reduce(
    (acc, val) => !val[1] ? acc : [...acc, val[0]], []
)

displayedCards = displayedCards.filter(card =>
    allowedExpansions.includes(card.Expansion) && (isBonusCard(card) || (
        allowedColors.includes(card.Color ? card.Color.toLowerCase() : 'white')) &&
        eatsFood(card, mustHaveFood) &&
        allowedNests.includes(card['Nest type'])
    )
)
```

What do you think?

**Comment by navarog** [comment]
Hi Touniouk,
great idea, should be implemented.
