### ISSUE TITLE
Expansions filter

### ISSUE THREAD

**Issue by krzysztof90** [navarog/wingsearch#28]
Unchecking base game at expansions filter list doesn't keep after page refresh. Is this a feature?

**Comment by navarog** [comment]
Yes, this is an intended feature for people that do not own all expansions so they do not need to uncheck them every time. If you delete the app data from the browser, you get the cookie consent pop-up. If you reject this option, then the selected language and expansions will refresh back to the default as well.

**Comment by krzysztof90** [comment]
Right, but I mean situation where you uncheck 'Base game'. Filter comes back to what you choose if you uncheck any other expansion. Base game is always checked, no matter what you chose before

**Comment by navarog** [comment]
You're right. At first I considered Base game to be always desirable but with the upcoming asia expansion people can play without it.

**Comment by navarog** [comment]
It should be fixed now.
