### ISSUE TITLE
Cards power text view

### ISSUE THREAD

**Issue by krzysztof90** [navarog/wingsearch#29]
For example Golden-Headed Cisticola bird displays its power text with dot on new line. Not nice.
By the way, I could fix some issues. Just don't know the way you work. If you want to delegate some tasks, let me know

**Comment by navarog** [comment]
If you want to contribute and fix those things by yourself, I'd be more than happy. I don't think I have a capacity to properly maintain it. Feel free to open a code review where you describe what specifically you fix with some screenshot of the changed cards as a reference for me and I'll have a look.
