### ISSUE TITLE
English text on Avid Asian Admirer card says "FIST" instead of "FIRST"

### ISSUE THREAD

**Issue by tcherna** [navarog/wingsearch#48]
Pretty much what the title says :)
<img width="254" alt="Screen Shot 2022-12-29 at 8 33 46 AM" src="https://user-images.githubusercontent.com/8117665/209982331-58c9e2f1-5fa4-4c92-9436-ce63f45423f8.png">

**Comment by navarog** [comment]
Fixed, thank you for pointing this out!
