### ISSUE TITLE
Here's some Asia birds silhouettes

### ISSUE THREAD

**Issue by gitHu6-newb** [navarog/wingsearch#80]
I started making .png silhouettes (4 so far), please take them from https://github.com/gitHu6-newb/imenages/tree/main/silhouettes

Let me know if I can improve them somehow to be more consistent with yours. I think I have found my groove making them. I'll be putting a more consistent gaussian blur at 4.5 on them like i did for #361

**Comment by navarog** [comment]
I think these are amazing! Can I take these you already did, or will you make a whole pull request later? And regarding the improvements, I think you got it pretty well. I have no clue what exactly I used back then; the Photoshop macro I created for that is lost on my old PC 🙂

**Comment by navarog** [comment]
About the placement/size issue: I did my silhouettes by roughly following these steps:
1. Scan the card
2. Crop the card to its intended dimensions (57x87)
3. Delete everything except the bird art
4. Convert all the remaining pixels, that is, the bird art, to a grey color
5. Apply gaussian blur
6. Save as PNG transparent

**Comment by navarog** [comment]
For consistency, I think you want to increase the Gaussian blur size a bit. But sadly, I did not document the precise size anywhere 🥲 But I think it looks great even as it is! No need to bother.
![image](https://github.com/navarog/wingsearch/assets/22467181/b1cc5c8e-3c14-449d-9da3-0885473cfb96)

**Comment by gitHu6-newb** [comment]
i went back and applied a bit more blur to the files :) Newer birds blur with value 7.5.
I am not scanning physical cards, but perspective transforming screenshots from an unboxing video. I used one of your png bird assets as a template for size, which was roughly 450 x 684~ish pixels. I dont know what units the 57x87 are in, and can't seem to find if that correlates to the 450x680 px. Please let me know if I need to make an adjustment.

And yes, just copy them over for your use. Sorry i dunno what a 'pull' is. I'll send u a message when I have completed them all.

**Comment by navarog** [comment]
Sounds great! I think your approach works just fine. Let me know then and I will add it all 👍

Many thanks!

**Comment by gitHu6-newb** [comment]
All Finished! 
I noticed you already had a silhouette for #374 so I skipped that number, but  all the rest are sequentially there.
I re-did the initial 4, so please grab those again as well.
omg the little grebe (407) looks like a turd with a head! LOL
