### ISSUE TITLE
some images cover the wingspan number

### ISSUE THREAD

**Issue by gitHu6-newb** [navarog/wingsearch#82]
I now noticed the actual physical cards sometimes place the wingspan statistic in slightly different places, so sometimes the wingsearch images and wingspan stat occupy the same area here. All the stable diffusion pics are fine. I've gone and nudged the affected silhouettes and robbie's birds into a better position (hopefully). 
https://github.com/gitHu6-newb/imenages/tree/main/adjustments

You may want to scrutinize the Trumpeter Swan (#235) and Robbie's American Coot (#5) a bit more because I'm not sure how much image scaling can happen so I was just guessing a lot on how much to move them.

Thanks!

**Comment by navarog** [comment]
I updated the app with the modifications and it looks better, thanks!
